### ISSUE TITLE
No host internet connection - Supervisor 2023.06.02

### ISSUE THREAD

**Issue by dgarciadonado** [home-assistant/operating-system#2602]
### Describe the issue you are experiencing

I use HAOS as a VM inside Proxmox. I use two ethernet connections (one with internet output 192.168.1.8 and the other one 192.168.10.8 without internet output)
 
I have recently realized that I cannot update any addon nor restore a backup from any addon. The error message that shows is:
'AddonManager.install' blocked from execution, no host internet connection'. Is suspect it is since HA Supervisor update to 2023.05.xx

Investigating with [ha interface info] I have the flag host_internet = false but everything is working as expected.

Please find below the full output. Just to mention that the DNS server in enp0s18 interface is a pihole with 192.168.1.20 I have tested disabling blocking in pihole without success. I have also tested using 1.1.1.1 or 8.8.8.8 as DNS but same error.

```
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: false
interfaces:
- connected: true
  enabled: true
  interface: enp0s18
  ipv4:
    address:
    - 192.168.1.8/24
    gateway: 192.168.1.1
    method: static
    nameservers:
    - 192.168.1.20
    ready: true
  ipv6:
    address:
    - fe80::7cba:8892:df61:95fc/64
    gateway: null
    method: disabled
    nameservers: []
    ready: true
  primary: true
  type: ethernet
  vlan: null
  wifi: null
- connected: true
  enabled: true
  interface: enp1s27u3
  ipv4:
    address:
    - 192.168.10.8/24
    gateway: 192.168.10.1
    method: static
    nameservers:
    - 192.168.10.1
    ready: true
  ipv6:
    address:
    - fe80::11b8:768f:e61f:6ca/64
    gateway: null
    method: disabled
    nameservers: []
    ready: true
  primary: false
  type: ethernet
  vlan: null
  wifi: null
supervisor_internet: true
```

It seems that DNS is working, because I can ping google and also if I execute:
curl https://version.home-assistant.io/online.txt
the result is:
NetworkManager is online

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Go to Settings/System/Update
2. Try to update any addon
3. Get the result: 'AddonManager.install' blocked from execution, no host internet connection'
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-19 01:56:50 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, no host internet connection
```

### Anything in the Host logs that might be useful for us?

```txt
Jun 18 23:56:12 homeassistant systemd[1]: mnt-data-docker-overlay2-177461f038af3b7074c95cbe49aaeea0c146754f9e4b35b404d2937155ee2686-merged.mount: Deactivated successfully.
Jun 18 23:56:13 homeassistant kernel: hassio: port 10(veth7d881f8) entered blocking state
Jun 18 23:56:13 homeassistant kernel: hassio: port 10(veth7d881f8) entered disabled state
Jun 18 23:56:13 homeassistant kernel: device veth7d881f8 entered promiscuous mode
Jun 18 23:56:13 homeassistant kernel: hassio: port 10(veth7d881f8) entered blocking state
Jun 18 23:56:13 homeassistant kernel: hassio: port 10(veth7d881f8) entered forwarding state
Jun 18 23:56:13 homeassistant NetworkManager[425]: <info>  [1687132573.1983] manager: (vetha97e54d): new Veth device (/org/freedesktop/NetworkManager/Devices/58)
Jun 18 23:56:13 homeassistant NetworkManager[425]: <info>  [1687132573.1998] manager: (veth7d881f8): new Veth device (/org/freedesktop/NetworkManager/Devices/59)
Jun 18 23:56:13 homeassistant systemd[1]: Started libcontainer container 8a494319575e5b4f70764e6fc259bb19c299b8da5c0f84c9b43bf5a0e5a3dd70.
Jun 18 23:56:13 homeassistant kernel: eth0: renamed from vetha97e54d
Jun 18 23:56:13 homeassistant kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth7d881f8: link becomes ready
Jun 18 23:56:13 homeassistant NetworkManager[425]: <info>  [1687132573.4928] device (veth7d881f8): carrier: link connected
Jun 18 23:56:18 homeassistant systemd[1]: docker-8a494319575e5b4f70764e6fc259bb19c299b8da5c0f84c9b43bf5a0e5a3dd70.scope: Deactivated successfully.
Jun 18 23:56:18 homeassistant systemd[1]: docker-8a494319575e5b4f70764e6fc259bb19c299b8da5c0f84c9b43bf5a0e5a3dd70.scope: Consumed 1.207s CPU time.
Jun 18 23:56:18 homeassistant kernel: kauditd_printk_skb: 88 callbacks suppressed
Jun 18 23:56:18 homeassistant kernel: audit: type=1334 audit(1687132578.821:694): prog-id=124 op=UNLOAD
Jun 18 23:56:18 homeassistant dockerd[506]: time="2023-06-18T23:56:18.835892965Z" level=info msg="ignoring event" container=8a494319575e5b4f70764e6fc259bb19c299b8da5c0f84c9b43bf5a0e5a3dd70 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 18 23:56:18 homeassistant kernel: audit: type=1325 audit(1687132578.849:695): table=nat:285 family=2 entries=1 op=nft_unregister_rule pid=14486 subj=unconfined comm="iptables"
Jun 18 23:56:18 homeassistant kernel: audit: type=1300 audit(1687132578.849:695): arch=c000003e syscall=46 success=yes exit=512 a0=3 a1=7ffd3b0b75c0 a2=0 a3=7ffd3b0b75ac items=0 ppid=506 pid=14486 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key=(null)
Jun 18 23:56:18 homeassistant kernel: audit: type=1327 audit(1687132578.849:695): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D74006E6174002D4400444F434B4552002D7000746370002D6400302F30002D2D64706F727400343433002D6A00444E4154002D2D746F2D64657374696E6174696F6E003137322E33302E33332E343A3434330000002D690068617373696F
Jun 18 23:56:18 homeassistant kernel: audit: type=1325 audit(1687132578.853:696): table=filter:286 family=2 entries=1 op=nft_unregister_rule pid=14488 subj=unconfined comm="iptables"
Jun 18 23:56:18 homeassistant kernel: audit: type=1300 audit(1687132578.853:696): arch=c000003e syscall=46 success=yes exit=652 a0=3 a1=7ffd089ef590 a2=0 a3=7ffd089ef57c items=0 ppid=506 pid=14488 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key=(null)
Jun 18 23:56:18 homeassistant kernel: audit: type=1327 audit(1687132578.853:696): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D740066696C746572002D4400444F434B45520000002D690068617373696F002D6F0068617373696F002D7000746370002D64003137322E33302E33332E34002D2D64706F727400343433002D6A00414343455054
Jun 18 23:56:18 homeassistant kernel: audit: type=1325 audit(1687132578.871:697): table=nat:287 family=2 entries=1 op=nft_unregister_rule pid=14490 subj=unconfined comm="iptables"
Jun 18 23:56:18 homeassistant kernel: audit: type=1300 audit(1687132578.871:697): arch=c000003e syscall=46 success=yes exit=604 a0=3 a1=7ffc8d637c60 a2=0 a3=7ffc8d637c4c items=0 ppid=506 pid=14490 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key=(null)
Jun 18 23:56:18 homeassistant kernel: audit: type=1327 audit(1687132578.871:697): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D74006E6174002D4400504F5354524F5554494E47002D7000746370002D73003137322E33302E33332E34002D64003137322E33302E33332E34002D2D64706F727400343433002D6A004D415351554552414445
Jun 18 23:56:18 homeassistant kernel: hassio: port 10(veth7d881f8) entered disabled state
Jun 18 23:56:18 homeassistant kernel: vetha97e54d: renamed from eth0
Jun 18 23:56:19 homeassistant NetworkManager[425]: <info>  [1687132579.0018] manager: (vetha97e54d): new Veth device (/org/freedesktop/NetworkManager/Devices/60)
Jun 18 23:56:19 homeassistant kernel: hassio: port 10(veth7d881f8) entered disabled state
Jun 18 23:56:19 homeassistant kernel: device veth7d881f8 left promiscuous mode
Jun 18 23:56:19 homeassistant kernel: hassio: port 10(veth7d881f8) entered disabled state
Jun 18 23:56:19 homeassistant systemd[1]: run-docker-netns-031cd2843551.mount: Deactivated successfully.
Jun 18 23:56:19 homeassistant systemd[1]: var-lib-docker-overlay2-3f36c0cc12fd54db3dc60773a7c04340b23daa496a5943af8a4988d57aba8885-merged.mount: Deactivated successfully.
Jun 18 23:56:19 homeassistant systemd[1]: mnt-data-docker-overlay2-3f36c0cc12fd54db3dc60773a7c04340b23daa496a5943af8a4988d57aba8885-merged.mount: Deactivated successfully.
Jun 19 00:00:09 homeassistant systemd[1]: var-lib-docker-overlay2-d72cf98b6b9a87c27730ef455f07446b8f1877540d287eb1be288cefb5efb84e\x2dinit-merged.mount: Deactivated successfully.
Jun 19 00:00:09 homeassistant systemd[1]: mnt-data-docker-overlay2-d72cf98b6b9a87c27730ef455f07446b8f1877540d287eb1be288cefb5efb84e\x2dinit-merged.mount: Deactivated successfully.
Jun 19 00:00:10 homeassistant systemd[1]: Started libcontainer container 27b62a7e91cea05094c3906a4f21a44344928581e77ce829020e8659d7037ee0.
Jun 19 00:00:10 homeassistant kernel: kauditd_printk_skb: 22 callbacks suppressed
Jun 19 00:00:10 homeassistant kernel: audit: type=1334 audit(1687132810.446:706): prog-id=128 op=LOAD
Jun 19 00:00:10 homeassistant kernel: audit: type=1334 audit(1687132810.447:707): prog-id=129 op=LOAD
Jun 19 00:00:10 homeassistant kernel: audit: type=1300 audit(1687132810.447:707): arch=c000003e syscall=321 success=yes exit=15 a0=5 a1=c0001357f8 a2=78 a3=0 items=0 ppid=16711 pid=16722 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jun 19 00:00:10 homeassistant kernel: audit: type=1327 audit(1687132810.447:707): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F32376236326137653931636561303530393463333930366134
Jun 19 00:00:10 homeassistant kernel: audit: type=1334 audit(1687132810.447:708): prog-id=130 op=LOAD
Jun 19 00:00:10 homeassistant kernel: audit: type=1300 audit(1687132810.447:708): arch=c000003e syscall=321 success=yes exit=17 a0=5 a1=c000135590 a2=78 a3=0 items=0 ppid=16711 pid=16722 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jun 19 00:00:10 homeassistant kernel: audit: type=1327 audit(1687132810.447:708): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F32376236326137653931636561303530393463333930366134
Jun 19 00:00:10 homeassistant kernel: audit: type=1334 audit(1687132810.447:709): prog-id=130 op=UNLOAD
Jun 19 00:00:10 homeassistant kernel: audit: type=1334 audit(1687132810.447:710): prog-id=129 op=UNLOAD
Jun 19 00:00:10 homeassistant kernel: audit: type=1334 audit(1687132810.447:711): prog-id=131 op=LOAD
Jun 19 00:08:17 homeassistant systemd-journald[164]: Data hash table of /var/log/journal/f9ecdd5796884edf9908d1868fc42b7c/system.journal has a fill level at 75.0 (85333 of 113777 items, 33554432 file size, 393 bytes per hash table item), suggesting rotation.
Jun 19 00:08:17 homeassistant systemd-journald[164]: /var/log/journal/f9ecdd5796884edf9908d1868fc42b7c/system.journal: Journal header limits reached or header out-of-date, rotating.
Jun 19 00:09:36 homeassistant systemd[1]: Starting Cleanup of Temporary Directories...
Jun 19 00:09:36 homeassistant systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Jun 19 00:09:36 homeassistant systemd[1]: Finished Cleanup of Temporary Directories.
Jun 19 00:09:36 homeassistant systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.
Jun 19 00:10:57 homeassistant systemd[1]: var-lib-docker-overlay2-223740f473b990ce427a9217efbf460cd6692bb812702880d0ec636e21397324\x2dinit-merged.mount: Deactivated successfully.
Jun 19 00:10:57 homeassistant systemd[1]: mnt-data-docker-overlay2-223740f473b990ce427a9217efbf460cd6692bb812702880d0ec636e21397324\x2dinit-merged.mount: Deactivated successfully.
Jun 19 00:10:57 homeassistant kernel: hassio: port 10(veth33d73b4) entered blocking state
Jun 19 00:10:57 homeassistant kernel: hassio: port 10(veth33d73b4) entered disabled state
Jun 19 00:10:57 homeassistant kernel: device veth33d73b4 entered promiscuous mode
Jun 19 00:10:57 homeassistant kernel: kauditd_printk_skb: 2 callbacks suppressed
Jun 19 00:10:57 homeassistant kernel: audit: type=1700 audit(1687133457.236:712): dev=veth33d73b4 prom=256 old_prom=0 auid=4294967295 uid=0 gid=0 ses=4294967295
Jun 19 00:10:57 homeassistant kernel: audit: type=1300 audit(1687133457.236:712): arch=c000003e syscall=44 success=yes exit=40 a0=c a1=c0014b32c0 a2=28 a3=0 items=0 ppid=1 pid=506 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="dockerd" exe="/usr/bin/dockerd" subj=unconfined key=(null)
Jun 19 00:10:57 homeassistant kernel: audit: type=1327 audit(1687133457.236:712): proctitle=2F7573722F62696E2F646F636B657264002D480066643A2F2F002D2D636F6E7461696E6572643D2F72756E2F636F6E7461696E6572642F636F6E7461696E6572642E736F636B
Jun 19 00:10:57 homeassistant NetworkManager[425]: <info>  [1687133457.2380] manager: (veth8be5bed): new Veth device (/org/freedesktop/NetworkManager/Devices/61)
Jun 19 00:10:57 homeassistant NetworkManager[425]: <info>  [1687133457.2391] manager: (veth33d73b4): new Veth device (/org/freedesktop/NetworkManager/Devices/62)
Jun 19 00:10:57 homeassistant kernel: audit: type=1325 audit(1687133457.259:713): table=nat:294 family=2 entries=1 op=nft_register_rule pid=22874 subj=unconfined comm="iptables"
Jun 19 00:10:57 homeassistant kernel: audit: type=1300 audit(1687133457.259:713): arch=c000003e syscall=46 success=yes exit=508 a0=3 a1=7ffef3802860 a2=0 a3=7ffef380284c items=0 ppid=506 pid=22874 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key=(null)
Jun 19 00:10:57 homeassistant kernel: audit: type=1327 audit(1687133457.259:713): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D74006E6174002D4100444F434B4552002D7000746370002D6400302F30002D2D64706F7274003530323234002D6A00444E4154002D2D746F2D64657374696E6174696F6E003137322E33302E33332E343A32320000002D690068617373696F
Jun 19 00:10:57 homeassistant kernel: audit: type=1325 audit(1687133457.261:714): table=filter:295 family=2 entries=1 op=nft_register_rule pid=22876 subj=unconfined comm="iptables"
Jun 19 00:10:57 homeassistant kernel: audit: type=1300 audit(1687133457.261:714): arch=c000003e syscall=46 success=yes exit=648 a0=3 a1=7ffd48d8f880 a2=0 a3=7ffd48d8f86c items=0 ppid=506 pid=22876 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-nft-multi" subj=unconfined key=(null)
Jun 19 00:10:57 homeassistant kernel: audit: type=1327 audit(1687133457.261:714): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D740066696C746572002D4100444F434B45520000002D690068617373696F002D6F0068617373696F002D7000746370002D64003137322E33302E33332E34002D2D64706F7274003232002D6A00414343455054
Jun 19 00:10:57 homeassistant kernel: audit: type=1325 audit(1687133457.264:715): table=nat:296 family=2 entries=1 op=nft_register_rule pid=22878 subj=unconfined comm="iptables"
Jun 19 00:10:57 homeassistant systemd[1]: Started libcontainer container 1c2a63cb90d6f36ab21675f523376e996d8c9e411840c833d0a3b3d2f58b5958.
Jun 19 00:10:57 homeassistant kernel: eth0: renamed from veth8be5bed
Jun 19 00:10:57 homeassistant kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth33d73b4: link becomes ready
Jun 19 00:10:57 homeassistant kernel: hassio: port 10(veth33d73b4) entered blocking state
Jun 19 00:10:57 homeassistant kernel: hassio: port 10(veth33d73b4) entered forwarding state
Jun 19 00:10:57 homeassistant NetworkManager[425]: <info>  [1687133457.5148] device (veth33d73b4): carrier: link connected
Jun 19 00:18:49 homeassistant kernel: kauditd_printk_skb: 38 callbacks suppressed
Jun 19 00:18:49 homeassistant kernel: audit: type=1334 audit(1687133929.189:730): prog-id=136 op=LOAD
Jun 19 00:18:49 homeassistant systemd-timesyncd[497]: Network configuration changed, trying to establish connection.
Jun 19 00:18:49 homeassistant systemd-timesyncd[497]: Contacted time server 162.159.200.123:123 (time.cloudflare.com).
Jun 19 00:18:49 homeassistant systemd[1]: Started Journal Gateway Service.
Jun 19 00:18:49 homeassistant systemd-journal-gatewayd[27482]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
Jun 19 00:20:48 homeassistant systemd[1]: docker-27b62a7e91cea05094c3906a4f21a44344928581e77ce829020e8659d7037ee0.scope: Deactivated successfully.
Jun 19 00:20:48 homeassistant systemd[1]: docker-27b62a7e91cea05094c3906a4f21a44344928581e77ce829020e8659d7037ee0.scope: Consumed 4.493s CPU time.
Jun 19 00:20:48 homeassistant kernel: audit: type=1334 audit(1687134048.443:731): prog-id=128 op=UNLOAD
Jun 19 00:20:48 homeassistant dockerd[506]: time="2023-06-19T00:20:48.457500564Z" level=info msg="ignoring event" container=27b62a7e91cea05094c3906a4f21a44344928581e77ce829020e8659d7037ee0 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 19 00:20:48 homeassistant kernel: audit: type=1334 audit(1687134048.460:732): prog-id=131 op=UNLOAD
Jun 19 00:20:48 homeassistant systemd[1]: var-lib-docker-overlay2-d72cf98b6b9a87c27730ef455f07446b8f1877540d287eb1be288cefb5efb84e-merged.mount: Deactivated successfully.
Jun 19 00:20:48 homeassistant systemd[1]: mnt-data-docker-overlay2-d72cf98b6b9a87c27730ef455f07446b8f1877540d287eb1be288cefb5efb84e-merged.mount: Deactivated successfully.
Jun 19 00:20:48 homeassistant systemd[1]: Started libcontainer container 8043ec458ba4cf9319ee4d80bc7ce86349746fa2e76442957a78969dbbadb280.
Jun 19 00:20:48 homeassistant kernel: audit: type=1334 audit(1687134048.783:733): prog-id=137 op=LOAD
Jun 19 00:20:48 homeassistant kernel: audit: type=1334 audit(1687134048.784:734): prog-id=138 op=LOAD
Jun 19 00:20:48 homeassistant kernel: audit: type=1300 audit(1687134048.784:734): arch=c000003e syscall=321 success=yes exit=15 a0=5 a1=c0001ad7f8 a2=78 a3=0 items=0 ppid=28681 pid=28691 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jun 19 00:20:48 homeassistant kernel: audit: type=1327 audit(1687134048.784:734): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F38303433656334353862613463663933313965653464383062
Jun 19 00:20:48 homeassistant kernel: audit: type=1334 audit(1687134048.784:735): prog-id=139 op=LOAD
Jun 19 00:20:48 homeassistant kernel: audit: type=1300 audit(1687134048.784:735): arch=c000003e syscall=321 success=yes exit=17 a0=5 a1=c0001ad590 a2=78 a3=0 items=0 ppid=28681 pid=28691 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jun 19 00:20:48 homeassistant kernel: audit: type=1327 audit(1687134048.784:735): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F38303433656334353862613463663933313965653464383062
Jun 19 00:20:48 homeassistant kernel: audit: type=1334 audit(1687134048.784:736): prog-id=139 op=UNLOAD
```

### Additional information

Executing nmcli g status the output is:
STATE                  CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
connected (site only)  limited       missing  enabled  missing  enabled

Executing nmcli the ouput is:
enp0s18: connected to Supervisor enp0s18
	"enp0s18"
	ethernet (virtio_net), 02:82:C1:AB:CF:2D, hw, mtu 1500
	ip4 default
	inet4 192.168.1.8/24
	route4 192.168.1.0/24 metric 100
	route4 default via 192.168.1.1 metric 20100
	inet6 fe80::7cba:8892:df61:95fc/64
	route6 fe80::/64 metric 1024

enp1s27u3: connected to Supervisor enp1s27u3
	"enp1s27u3"
	ethernet (ax88179_178a), 00:0E:C6:DE:3E:8A, hw, mtu 1500
	inet4 192.168.10.8/24
	route4 192.168.10.0/24 metric 101
	route4 default via 192.168.10.1 metric 20101
	inet6 fe80::11b8:768f:e61f:6ca/64
	route6 fe80::/64 metric 1024

docker0: unmanaged
	"docker0"
	bridge, 02:42:59:B9:8C:86, sw, mtu 1500

hassio: unmanaged
	"hassio"
	bridge, 02:42:F6:D5:A6:00, sw, mtu 1500

veth33d73b4: unmanaged
	"veth33d73b4"
	ethernet (veth), 06:58:07:83:EE:96, sw, mtu 1500

veth40a15d6: unmanaged
	"veth40a15d6"
	ethernet (veth), DA:4A:8C:BF:BB:18, sw, mtu 1500

veth5c01744: unmanaged
	"veth5c01744"
	ethernet (veth), 32:DF:99:05:FB:51, sw, mtu 1500

veth9f0aa35: unmanaged
	"veth9f0aa35"
	ethernet (veth), AE:58:D8:68:E6:51, sw, mtu 1500

vethbe18d9a: unmanaged
	"vethbe18d9a"
	ethernet (veth), 7E:EF:07:8B:F8:75, sw, mtu 1500

vethc3c856c: unmanaged
	"vethc3c856c"
	ethernet (veth), 02:18:5D:0D:99:E4, sw, mtu 1500

vethc8e9dbd: unmanaged
	"vethc8e9dbd"
	ethernet (veth), EA:97:09:54:37:6E, sw, mtu 1500

vethd84608c: unmanaged
	"vethd84608c"
	ethernet (veth), 3A:FC:01:FB:BA:01, sw, mtu 1500

vethf331410: unmanaged
	"vethf331410"
	ethernet (veth), EE:1D:D1:9A:BB:FF, sw, mtu 1500

vethfd9d03e: unmanaged
	"vethfd9d03e"
	ethernet (veth), 5E:34:2F:82:BE:0D, sw, mtu 1500

vethff5c6d8: unmanaged
	"vethff5c6d8"
	ethernet (veth), 2A:AE:5F:92:84:7F, sw, mtu 1500

vethffcc42d: unmanaged
	"vethffcc42d"
	ethernet (veth), 46:67:15:78:FA:12, sw, mtu 1500

lo: unmanaged
	"lo"
	loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536

DNS configuration:
	servers: 192.168.1.20
	interface: enp0s18

	servers: 192.168.10.1
	interface: enp1s27u3

**Comment by dgarciadonado** [comment]
Thank you for your fast answer!
Just checked and it seems that I can access:

![image](https://github.com/home-assistant/operating-system/assets/46694046/b783b0e5-1280-4b93-ab52-65c6204db31a)

My DNS server (192.168.1.20) is provided by a pi-hole in a raspberry pi. I have disabled Blocking on pihole but nothing change. Maybe is another option I need to change in pi-hole but for me it is weird because it has been working with this configuration various months/years.

Thank you again!

**Comment by Taaitaaiger** [comment]
Have you tried manually setting the date? I've been struggling with the same issue and I think I just fixed it that way (because according to the logs a docker image is currently being downloaded).

`date --set="YYYY-MM-DD HH:MM"`

**Comment by dgarciadonado** [comment]
Thank you for the tip! I applied on the VM inside proxmox but unfortunately didn't work. Any other option to see?
Any other log that should be useful and I can provide?
Thanks!

**Comment by donkeykangwang10** [comment]
I have the same issue, my device is X86-64. my host_internet and supervisor_internet are all false. I have no idea.

**Comment by home110120** [comment]
Same here. Both host and supervisor internet are false, on a VM of Synology NAS, and I did not apply any customized setting on HA, it use DHCP to get a constant IP as defined on my router, and nothing changed recently on network environment. The only abnormal is that supervisor failed to initiate in the past several month, sometimes everything is just fine with a reboot.

**Comment by harfordhawk** [comment]
Not sure , but for me, OS10 still does not work.  I use proxmox 7 vm inside.  Multitude of connectivity problems , high processor usage, etc.. I reverted back to OS 9.5

**Comment by dgarciadonado** [comment]
Please, could you point me how to revert to OS 9.5?
Or you just restore and old backup with that OS?
Thanks!

**Comment by harfordhawk** [comment]
pretty sure the command is ha os update --version 9.5

in the console

**Comment by dgarciadonado** [comment]
Thanks! I have reverted with the command you have proposed and right now I have connectivity but I cannot update addons nor supervisor.
![image](https://github.com/home-assistant/operating-system/assets/46694046/2b729a57-5167-4e65-8e55-4e852d165813)

Investigating, maybe the issue it could be related with the fact that I cannot fully disable IPV6.
It shows disabled in both interfaces:
![image](https://github.com/home-assistant/operating-system/assets/46694046/208ac496-6cbd-47fa-bd93-14dd98a88e3a)
But I have an IPV6 ip;
![image](https://github.com/home-assistant/operating-system/assets/46694046/5fc951e1-e139-4b1e-9215-153f8826b640)

If I check both interfaces with nmcli IPV6 is in mode link-local:
![image](https://github.com/home-assistant/operating-system/assets/46694046/6e739982-f3b5-4885-b80b-cfa0e57a98dc)

and if I try to disable with nmcli command this is the result (which to be honest I don't understand why the response is related to ipv4-dns parameter instead of ipv6-method):
![image](https://github.com/home-assistant/operating-system/assets/46694046/5db0abf2-6b36-4b42-ab37-7a4baceb0bed)

Any kindly hint?
Thanks!!
