### ISSUE TITLE
HassOS data resizing timeout

### ISSUE THREAD

**Issue by agners** [home-assistant/operating-system#3365]
**Fresh install** on a Lenovo M90n-IoT with an i3, 4gb ram and a 128gb low-performance NVMe SSD.
Computer had windows before on the drive.
Booted Ubuntu Live, and used Disk to restore and image (HAOS 12.2) as per HA tutorial.
After 1m30s, timeout to resize the data partition:
`[DEPEND] Dependency failed for HassOS data resizing.`

Command line (From CTRL-ALT-F2) with blkid showed part p8 to be correctly labeled (hassos-data)
Ping to 8.8.8.8 and local network worked.

**What worked:**
Booted Ubuntu Live, used Disk to FORMAT DISK, with option "empty no partitions" and "slow write zeroes everywhere". Then used Disk to restore an image (HAOS 12.2) as per HA tutorial.

On bootup, resizing the SWAP took 30s, resizing data was so fast I did not see going trough (so, less than 2s).
...
and now it works.

I'm enclined to say it's a bug, as strictly following instructions gives a dead-end.
Maybe the data resizing needs more time on a non-zeroed disk to perform the duty?
Why put a timeout anyway, if the whole thing fails when it fails??
If zeroing the disk is critical, probably something important is incorrectly defined in the disk image? Like not zeroing a trailing sector after a partition table that can add garbage to it?

Anyway, that is my first welcome to HA, and it's already a bug hunt.
Hope this helps other users and devs! :)

_Originally posted by @LionRelaxe in https://github.com/home-assistant/operating-system/issues/2272#issuecomment-2077001018_

**Comment by bryanvaz** [comment]
+1

This issue bogged me down for 4 hours because SSD was previously used as a VM storage drive. Did a `dd if=/dev/zero` then reimaged, and the new image immediately booted into the HA cli, no delay or timeout for the resizing step.

**Comment by BradB111** [comment]
+1

Trying to use a Zima board with an eMMC and this is the first time I've come across anything that reflects my experience, I have not been able to install HAOS yet however I'm mid way through a zero write. 

I would like to echo the thoughts of @LionRelaxe. A timeout during a one time setup doesn't seem necessary.

**Comment by LionRelaxe** [comment]
Please! Don't let this expire :)
I would fix this myself if I knew how...

**Comment by BradB111** [comment]
> Please! Don't let this expire :) I would fix this myself if I knew how...

This needs to be fixed in the installer to allow a much longer or no timeout for the process it gets stuck on.

In the meantime if you 0 write the drive you are tying to install it on it should allow for quicker installation to get through the section before the timeout. Worked straight away.

**Comment by ilspleno** [comment]
> > Please! Don't let this expire :) I would fix this myself if I knew how...
> 
> This needs to be fixed in the installer to allow a much longer or no timeout for the process it gets stuck on.
> 
> In the meantime if you 0 write the drive you are tying to install it on it should allow for quicker installation to get through the section before the timeout. Worked straight away.

THANK YOU. I spent 3-4 hours banging my head against this. Zero writing the drive fixed it for me too. 

Homelabbers frequently repurpose hardware, the "installer" should handle this better.

**Comment by LionRelaxe** [comment]
Bump.
Please, remove the data resizing timeout!
Keep up the good work :)

**Comment by DestrinStorm** [comment]
Just to add more votes/traffic.  My first exposure to trying to setup HA today was running into this bug - it's very not clear what was going on but a zero format on the drive did eventually fix it and get me to a working boot.  This is currently going to be a potential hard stop for users setting up on 'spare' hardware who don't know to go diving into the guts to work out why, should be fixed to make for a cleaner install

**Comment by marurup** [comment]
I've also just stumbled upon this now, trying to repurpose a old laptop (previously running manjaro linux).
Doing a #dd if=/dev/zero of=/dev/sdX" also fixed it for me.

For me the whole destination disk needed to be wiped/zero'ed.
I tried to "cheat" the first time and only wiped/zero'ed the 1GB or so, but that DID NOT WORK.

If not fixed in the install/update script, then it should be added to the instructions at https://www.home-assistant.io/installation/generic-x86-64

This was with image 16.1 (https://github.com/home-assistant/operating-system/releases/download/16.1/haos_generic-x86-64-16.1.img.xz)

**Comment by BradB111** [comment]
As far as I'm aware this is still an issue that needs to be addressed

**Comment by pmcanseco** [comment]
Hello, I'd like to add a datapoint that I was experiencing the exact symptoms of the OP. I was using an old PC with an SSD that previously had other data on it. I restored the disk image as in the documentation for installing through Ubuntu, but it would then fail to resize with the same error message. Doing as they said and zeroing out the drive, and then following the documentation for installing through Ubuntu worked. There is absolutely some kind of bug in the installer when the drive is not zeroed out (or quick formatted) but the image is restored onto it.

**Comment by govido** [comment]
+1 for this issue, I used a SSD that was previously used for Windows and Linux test installs.
I tried pretty much all formatting software I could find, wiping partitions, reformatting to NTFS, "SSD wipe", writing 60GB of data, reimaging... nothing worked. The only way was to zero the entire drive, which is just a very bad idea for a SSD.
As HA is meant to be used headless and the installation instructions send you straight to the web ui, this is pretty bad.
Even if you have a micro HDMI adapter handy and a screen nearby, you don't get any usable error at all.

**Comment by denalena** [comment]
experienced this with a 32gb micro sd and a raspberry 4b

Filling the card with /dev/zero worked but I still don't understand why this was necessary

**Comment by taryujiai** [comment]
experienced this as well.

generic chinese nuc from amazon. previously running freebsd. nvme drive.

ran the ubuntu boot -> restore image process. 

things I noticed:
correctly created the 8 partitions.
on first boot resized partition 8 (hassos-data) to the correct size.

hassos-data was never able to mount correctly.

On reboot into ubuntu running gparted -> saw partition 8 just fine (labelled correctly, disk checks pass).
running the Ubuntu disks program did not work. Was always an Unknown Filesystem.

Not sure what or how the two programs see things differently or get their info but someone more knowledgeable might understand the issue.

ran /dev/zero and like everyone else worked flawlessly.

**Comment by Joelious** [comment]
Hi!
New install on an old laptop. Same issue and zeroing fixed it. Commenting to highlight the issue.

Keep up the good work @entire ha team, and also thank you to the kind person sharing the workaround. 

Cheers!

**Comment by CygnusX2112** [comment]
Just contributing my "me too" comment to keep this open. I dont spend a lot of time building Linux systems that aren't a prebuilt image usung deployment agents and have thusly spent the last two days trying to figure out why I couldn't get this deployed after following the instructions exactly multiple times. 

Zeroing the disk solved my problem. Hassos otherwise would hang at the resize or mount stage.

**Comment by agners** [comment]
@CygnusX2112 what type of storage were you using?

I've tried various dirty disk images in a virtual machine, and I could not reproduce any resize issues here.

**Comment by CygnusX2112** [comment]
512GB M.2 SSD

**Comment by BradB111** [comment]
> +1
> 
> Trying to use a Zima board with an eMMC and this is the first time I've come across anything that reflects my experience, I have not been able to install HAOS yet however I'm mid way through a zero write.
> 
> I would like to echo the thoughts of [@LionRelaxe](https://github.com/LionRelaxe). A timeout during a one time setup doesn't seem necessary.
> 
> UPDATE: 0 write worked


I'd like to just add additional clarity to this now I've had more experience with HaOS. On physical hardware I have available to me suitable for HaOS i.e. lower powered devices. 

e.g. Zima Board and older atom based mini pc 

This resizing issue has been the case in all instances I've attempted to install HaOS direct onto physical hardware ranging from eMMC SSD and HDD. I can't confirm if this is the case on VMs as I've never tried.

The drives' previous content before a standard wipe and partition creation has either been misc storage or has been a windows boot drive in it's previous live. However, in all cases a 0 write has been successful in terms of rectifying the issue.

**Comment by Holigamer** [comment]
Still an issue. Im gonna write down my observations, because I started with a zeroed out drive and did a classic user error which led me to experience the same issue as @LionRelaxe.  

Maybe while #4772 is written, a note in https://www.home-assistant.io/installation/generic-x86-64#method-1-installing-haos-via-ubuntu-booting-from-a-usb-flash-drive to make sure the drive is reformatted with zeros before installing would be nice?

For me, I have a 480GB sata ssd and attempt to install onto a laptop.

**What I did:**
- Install HAOS using the generic method with Ubuntu Live
- Create a partition 9 using the remaining space on disk (because I though why not, what could break 🫠️)
- Boot HAOS
  - Resize did nothing (finished directly) since there was no further space for hassos-data
  - Install of core failed because hassos-data was too small
- Go back to Ubuntu Live and format disk (fast variant)
- Restore disk image again now with ~478GB of free space following hassos-data
- Boot HAOS
  - Now the resize operation times out
  - Using the method I found [here](https://community.home-assistant.io/t/waiting-for-home-assistant-cli-to-be-ready/635234) I got into the console and checked that indeed the resize has timed out but the disk was there (in journalctl)
- Further reinstalls with a fast disk format failed (the issue is repeatable)

**What worked for me:**
- Doing a **zero pass** on the ssd in Ubuntu Live
- Follow the generic HAOS install method with Ubuntu Live from there
- Time to expand is now <15s 

Best :)

**Comment by agners** [comment]
@Holigamer thank you for your detailed report, this is another datapoint confirming that zeroing out helps, and it is most likely related to a simple timeout due to slow writes during the grow operation.

I've tried to simulate it, but I guess this needs real-world random writes over time to cause fragmentation etc. and the necessary slowdown.

> Doing a **zero pass** on the ssd in Ubuntu Live

What do you mean exactly by "zero pass"? `dd` to zero out the disk?

Meanwhile there is this task which might solve the problem: https://github.com/home-assistant/operating-system/issues/4772.

> [!IMPORTANT]
>  If someone runs into this resizing issue, before using `dd` to zero out, right after flashing HAOS (before rebooting): If you feel comfortable in Linux shell, can you please try these commands after writing the HAOS image:
> 
> 
> ```
> DEV=sdX # ADJUST to device you've flashed HAOS to
> PART=8 # default data partition
> 
> start=$(cat /sys/class/block/$DEV/$DEV$PART/start)   # part start, 512B sectors
> size=$(cat /sys/class/block/$DEV/$DEV$PART/size)     # part size,  512B sectors
> disk=$(cat /sys/class/block/$DEV/size)               # whole-disk, 512B sectors
> 
> gap_start=$(( start + size ))                         # first free sector after data
> gap_sectors=$(( disk - 33 - gap_start ))             # stop before the backup GPT
> 
> blkdiscard --offset $(( gap_start * 512 )) --length $(( gap_sectors * 512 )) /dev/$DEV
> 
> ```
> 
> This simulate what `systemd-repart` would do, and hence confirm that this would resolve the underlying issue.

**Comment by LionRelaxe** [comment]
[@agners]
>thank you for your detailed report, this is another datapoint confirming that zeroing out helps, and it is most likely related to a simple timeout due to slow writes during the grow operation. 

I would like to point out that the issue is two-fold:
-Growing takes too much time; you seem to be tackling this part fine!
-There is a timeout for no valid reasons. If it fails, there is no need to continue. The install is botched and the system is unusable. Why not just delete that timeout? Let it work for as long as needed!

I'm hopefull that systemd-repart will alleviate this, but I'm worried that it will happen again in the future... new storage technologies, people installing HAOS on antique potatoes, etc... 

Make it fast, but delete the timeout please!
There would be no issue here, just a note in a forum: "resizing can take up to an hour, be patient".

Thanks for your work @agners !

**Comment by agners** [comment]
> -There is a timeout for no valid reasons. If it fails, there is no need to continue. The install is botched and the system is unusable.

Hm, that didn't always use to be the case. The data partition was just smaller, but the system still worked. But I guess with #4764 in place this is indeed true, and with that in mind removing the timeout is really the only thing which makes sense I agree.

**Comment by Holigamer** [comment]
Nice. Thank you for your work @agners!
Just to answer your question: I used the Erase Button in the disks utility (which I guess uses dd internally?)

<img width="728" height="541" alt="Image" src="https://github.com/user-attachments/assets/73e45987-8ea7-417e-9c89-4c010f9bcefe" />

Best :)

**Comment by Thomvh** [comment]
Still running into this issue on the 18.1 build. It seems two jobs runs for extending the data filesystem. One has no limit. The other has a 1 minute 30 limit and times out on a large disk.

**Comment by agners** [comment]
@Thomvh do you happen to have system logs of that situation? E.g. using `login` to get to the OS shell and get the service name which ultimately times out (`journalctl -b 0 | grep timeout` or something along these lines).
